version: 2
.conan-steps: &conan-steps
  steps:
    - checkout
    - run:
        name: Update Conan package
        command: .travis/install.sh
    - run:
        name: Build recipe
        command: .travis/run.sh

jobs:
  xcode8:
    macos:
      xcode: "8.3.3"
    environment:
      - CONAN_APPLE_CLANG_VERSIONS: "8.1"
    <<: *conan-steps

  xcode9:
    macos:
      xcode: "9.0"
    environment:
      - CONAN_APPLE_CLANG_VERSIONS: "9.0"
    <<: *conan-steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - xcode8
      - xcode9
